# NUMPY. Numerical Computing with Python


# Exercises

1) In the following table we have expression values for 5 genes at 4 time points. 

In [6]:
from IPython.lib import display as dp
%cat 'genes.csv' 
dp.FileLink('genes.csv')

Gene name,4h,12h,24h,48h
A2M,0.12,0.08,0.06,0.02
FOS,0.01,0.07,0.11,0.09
BRCA2,0.03,0.04,0.04,0.02
CPOX,0.05,0.09,0.11,0.14

/Users/eloi/Dropbox/PostGrauDataScience/DataScience-Course5/DataScience5-Solutions/genes.csv

   - Create a single array for the data (4x4)
   - Find the mean value per gene
   - Find the mean value per time point
   - Which gene has the maximum mean expression value? (return the whole gene row)

In [7]:
import numpy as np
gen_a = np.genfromtxt('genes.csv',delimiter=',',skip_header=1, usecols=[1,2,3,4])
#rows -> axis = 1
np.mean(gen_a,axis=1)

array([ 0.07  ,  0.07  ,  0.0325,  0.0975])

In [5]:
#columns -> axis = 0
np.mean(gen_a,axis=0)

array([ 0.0525,  0.07  ,  0.08  ,  0.0675])

In [6]:
gen_a[np.argmax(np.mean(gen_a,axis=1))]

array([ 0.05,  0.09,  0.11,  0.14])

<div class="alert alert-info">`ipythonblocks` is a teaching tool that allows students to experiment with Python flow control concepts and immediately see the effects of their code represented in a colorful, attractive way. BlockGrid objects can be **indexed and sliced like 2D NumPy arrays** making them good practice for learning how to access arrays. </div>

In [3]:
import numpy as np
import os
os.chdir('./modules/')
from ipythonblocks import BlockGrid
from ipythonblocks import colors
os.chdir('..')
grid = BlockGrid(8, 8, fill=(123, 234, 123))
grid.show()

In [4]:
a = np.zeros([8,8],dtype='int64')
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
grid[0, 0] #access to [0,0] element

Block(123, 234, 123, size=20)

In [6]:
grid[0:2,:] = colors['Teal']
grid.show()

In [7]:
a[0:2,:] = 1
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
grid[2,1:] = colors['Blue']
grid.show()

In [9]:
a[2,1:] = 2
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
grid[:2,2:3] = colors['Peru']
grid.show()

In [11]:
a[:2,2:3] = 3
a

array([[1, 1, 3, 1, 1, 1, 1, 1],
       [1, 1, 3, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
grid[:,::2] = colors['Peru']
grid.show()

In [13]:
a[:,::2] = 4
a

array([[4, 1, 4, 1, 4, 1, 4, 1],
       [4, 1, 4, 1, 4, 1, 4, 1],
       [4, 2, 4, 2, 4, 2, 4, 2],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0]])

In [14]:
grid[::2,::3] = colors['Red']
grid.show()

In [15]:
a[::2,::3] = 5
a

array([[5, 1, 4, 5, 4, 1, 5, 1],
       [4, 1, 4, 1, 4, 1, 4, 1],
       [5, 2, 4, 5, 4, 2, 5, 2],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [5, 0, 4, 5, 4, 0, 5, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [5, 0, 4, 5, 4, 0, 5, 0],
       [4, 0, 4, 0, 4, 0, 4, 0]])

2) Build a graphical representation of all multiple of 3 numbers from 0 to 49 by using exclusively the slicing operator (no iterations). 

In [16]:
grid = BlockGrid(50, 1, block_size=10, fill=(123, 234, 123))
# Your solution here
grid[0,2::3]=colors['Teal']
grid.show()

3) Build a graphical representation of a chessboard 8x8 by using exclusively the slicing operator (no iterations).

In [17]:
grid = BlockGrid(8, 8, block_size=20, fill=(0, 0, 0))
# Your solution here
grid[::2,::2] = colors['White']
grid[1::2,1::2] = colors['White']
grid.show()

4) Build a graphical representation of the prime numbers from 0 to 4999. (Hint: Compute the list of prime numbers and map this list to the grid representation).

In [20]:
grid = BlockGrid(50, 100, block_size=10, fill=(123, 234, 123))
# Your solution here

def sieveOfEratosthenes(n):
    """sieveOfEratosthenes(n): return the list of the primes < n."""
    # Code from: <dickinsm@gmail.com>, Nov 30 2006
    # http://groups.google.com/group/comp.lang.python/msg/f1f10ced88c68c2d
    if n <= 2:
        return []
    sieve = list(range(3, n, 2))
    top = len(sieve)
    for si in sieve:
        if si:
            bottom = (si*si - 3) // 2
            if bottom >= top:
                break
            sieve[bottom::si] = [0] * -((bottom - top) // si)
    return [2] + [el for el in sieve if el]

primelist = np.array(sieveOfEratosthenes(5000))
for p in primelist:
    grid[p/50.,p%50-1]= colors['Teal']
grid.show()

# Boolean Indexing doesn't work with blocks!
#mask = np.zeros([5000,1],dtype=bool)
#mask[primelist]= True
#mask = mask.reshape(50,100)
#grid[mask]=colors['Teal']
#grid.show


IndexError: Invalid index.